# Generated by Django 4.2.5 on 2024-02-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datafortress', '0005_video_creator_alter_notification_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='creator',
        ),
    ]
