# Generated by Django 4.2.5 on 2024-02-06 17:06

import datafortress.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafortress', '0008_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=datafortress.models.video_file_path),
        ),
    ]
